name: CI

on:
  push:

jobs:
  get-all-days:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: echo "matrix=$(ls -d ./Day*/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  tests:
    needs: get-all-days
    name: Run tests
    runs-on: ubuntu-latest

    container:
      env:
        STACK_ROOT: /root/.stack
      image: haskell:9.4.8-slim

    strategy:
      matrix:
        dir: ${{ fromJson(needs.get-all-days.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: make test
        working-directory: ${{ matrix.dir }}
